# yaml-language-server: $schema=https://golangci.github.io/legacy-v1-doc/jsonschema/golangci.jsonschema.json

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - gofumpt