project_id: '491513'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
  # JSON translation files
    {
        source: '/i18n/locales/en/data.json',
        translation: '/i18n/locales/%two_letters_code%/data.json',
    },
]