{{- if and .Values.initData.enabled (not .Values.initData.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "casdoor.initDataSecretName" . }}
  labels:
    {{- include "casdoor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "casdoor.initDataKey" . }}: |
    {{- .Values.initData.data | toPrettyJson | nindent 4 }}
{{- end }}
