import * as React from "react";
import i18next from "i18next";
import {useParams} from "react-router-dom";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {SimpleEditPage, type EditField} from "@/components/crud/SimpleEditPage";
import {useAccount} from "@/hooks/use-account";
import {useApplicationOptions, useGroupOptions, useOrganizationOptions} from "@/hooks/use-options";
import {InvitationSend} from "@/components/user/InvitationSend";
import * as OrganizationBackend from "@/backend/OrganizationBackend";
import * as InvitationBackend from "@/backend/InvitationBackend";
import {enumOptions, INVITATION_STATES} from "@/lib/enum-labels";
import * as Setting from "@/lib/setting";


/**
 * A plan's own invitation is generated by the backend; the antd page locks its
 * organization and name so the plan can still find it.
 */
const PLAN_INVITATION_TAG = "auto_created_invitation_for_plan";
const isCreatedByPlan = (ctx: {record: any}) => ctx.record.tag === PLAN_INVITATION_TAG;

export default function InvitationEditPage() {
  const {organizationName = "", invitationName = ""} = useParams();
  const {account} = useAccount();
  const organizations = useOrganizationOptions();
  const applications = useApplicationOptions(organizationName);
  const groups = useGroupOptions(organizationName);
  // copySignupLink needs each organization's defaultApplication, which the option
  // list does not carry, so the raw objects are fetched alongside it
  const [organizationObjs, setOrganizationObjs] = React.useState<any[]>([]);

  React.useEffect(() => {
    if (!Setting.isAdminUser(account)) {
      return;
    }
    OrganizationBackend.getOrganizations("admin").then((res: any) => {
      if (res.status === "ok") {
        setOrganizationObjs(res.data ?? []);
      }
    });
  }, [account]);

  /**
   * The invite link antd's "Copy signup page URL" builds: the organization's
   * default application's signup page, carrying this invitation's default code.
   */
  const copySignupUrl = (record: any) => {
    let defaultApplication = record.application;
    if (!defaultApplication || defaultApplication === "All") {
      const organization = organizationObjs.find((item: any) => item.name === record.owner);
      defaultApplication = organization?.defaultApplication;
      if (!defaultApplication) {
        Setting.showMessage(
          "error",
          i18next.t("invitation:You need to first specify a default application for organization: ") + record.owner,
        );
        return;
      }
    }
    Setting.copyToClipboard(
      `${window.location.origin}/signup/${defaultApplication}?invitationCode=${record.defaultCode ?? ""}`,
    );
  };

  const fields: EditField[] = [
    {
      type: "select",
      name: "owner",
      labelKey: "general:Organization",
      options: () => organizations,
      disabled: (ctx) => !Setting.isAdminUser(account) || isCreatedByPlan(ctx),
    },
    {type: "text", name: "name", labelKey: "general:Name", required: true, disabled: isCreatedByPlan},
    {type: "text", name: "displayName", labelKey: "general:Display name"},
    {type: "text", name: "code", labelKey: "invitation:Code"},
    {
      type: "custom",
      name: "defaultCode",
      labelKey: "invitation:Default code",
      render: (ctx, update) => (
        <div className="flex items-center gap-2">
          <Input
            value={ctx.record.defaultCode ?? ""}
            onChange={(e) => update("defaultCode", e.target.value)}
          />
          <Button variant="outline" className="shrink-0" onClick={() => copySignupUrl(ctx.record)}>
            {i18next.t("application:Copy signup page URL")}
          </Button>
        </div>
      ),
    },
    {type: "number", name: "quota", labelKey: "invitation:Quota"},
    {type: "number", name: "usedCount", labelKey: "invitation:Used count", disabled: () => true},
    {
      type: "select",
      name: "application",
      labelKey: "general:Application",
      options: () => [{value: "All", label: i18next.t("general:All")}, ...applications],
    },
    {type: "select", name: "signupGroup", labelKey: "provider:Signup group", options: () => groups},
    {type: "text", name: "username", labelKey: "signup:Username"},
    {type: "email", name: "email", labelKey: "general:Email"},
    {type: "text", name: "phone", labelKey: "general:Phone"},
    {
      type: "custom",
      name: "send",
      labelKey: "general:Send",
      block: true,
      render: (ctx) => (
        <InvitationSend invitation={ctx.record} organizations={organizationObjs} isAdd={ctx.mode === "add"} />
      ),
    },
    {
      type: "select",
      name: "state",
      labelKey: "general:State",
      options: () => enumOptions(INVITATION_STATES),
    },
  ];

  return (
    <SimpleEditPage
      titleKey="invitation:Edit Invitation"
      backTo="/invitations"
      deps={[organizationName, invitationName]}
      fields={fields}
      fetch={() => InvitationBackend.getInvitation(organizationName, invitationName)}
      add={(record) => InvitationBackend.addInvitation(record)}
      update={(record) => InvitationBackend.updateInvitation(organizationName, invitationName, record)}
      editUrl={(record) => `/invitations/${record.owner}/${record.name}`}
    />
  );
}
