project_id: '463556'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/src/locales/en/**/*',
      translation: '/src/locales/%two_letters_code%/**/%original_file_name%',
    },
  ]
