project_id: '463556'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/web/src/locales/en/data.json',
      translation: '/web/src/locales/%two_letters_code%/data.json',
    },
  ]
